on:
  push:
    branches:
      - main

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up our JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

#      - name: Install NATS
#        run: |
#          apt-get install curl
#          curl -L https://github.com/nats-io/nats-server/releases/download/vX.Y.Z/nats-server-vX.Y.Z-linux-amd64.zip -o nats-server.zip
#          unzip nats-server.zip -d nats-server
#          sudo cp nats-server/nats-server-vX.Y.Z-linux-amd64/nats-server /usr/bin
#
#      - name: Install Mongo
#        run: |
#          apt-get install gnupg curl
#          curl -fsSL https://pgp.mongodb.com/server-7.0.asc | \
#          sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
#          --dearmor
#          echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
#          sudo apt-get update
#          sudo apt-get install -y mongodb-org
#          systemctl start mongod
#          mongosh

      - name: Run application container
        run: |
          ls
          cp ./docker-compose.yml ./docker-compose.override.yml
          docker-compose down
          docker system prune -a -f
          docker-compose up

      - name: Test
        run: ./gradlew test
